{
  "$schema": "node_modules/wrangler/config-schema.json",
  "assets": {
    "binding": "ASSETS",
    "directory": "./dist/assets",
    "html_handling": "drop-trailing-slash",
    "not_found_handling": "404-page",
    "run_worker_first": false
  },
  "compatibility_date": "2026-03-15",
  "compatibility_flags": ["nodejs_compat", "no_handle_cross_request_promise_resolution"],
  "d1_databases": [
    {
      "binding": "DB_LIBRARY",
      "database_id": "${obj.RETROASSEMBLY_BUILD_TIME_WRANGLER_DATABASE_ID ?? '-'}",
      "database_name": "retroassembly_library",
      "migrations_dir": "src/databases/migrations"
    }
  ],
  "main": "./src/server/workerd.ts",
  "name": "retroassembly",
  "observability": {
    "enabled": true,
    "head_sampling_rate": 1
  },
  "placement": {
    "mode": "smart"
  },
  "preview_urls": true,
  "r2_buckets": [
    {
      "binding": "BUCKET",
      "bucket_name": "retroassembly",
      "preview_bucket_name": "retroassembly"
    }
  ],
  "services": [
    {
      "binding": "MSLEUTH",
      "service": "msleuth"
    }
  ],
  "upload_source_maps": true
}
